//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GQNA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GQNAEntities3 : DbContext
    {
        public GQNAEntities3()
            : base("name=GQNAEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_CD> tbl_CD { get; set; }
        public virtual DbSet<tbl_DT> tbl_DT { get; set; }
        public virtual DbSet<tbl_get_CD> tbl_get_CD { get; set; }
        public virtual DbSet<tbl_img> tbl_img { get; set; }
        public virtual DbSet<tbl_NHT> tbl_NHT { get; set; }
        public virtual DbSet<tbl_QG> tbl_QG { get; set; }
    }
}
