//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GQNA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NHT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_NHT()
        {
            this.tbl_QG = new HashSet<tbl_QG>();
        }
    
        public int id_NHT { get; set; }
        public string user_NHT { get; set; }
        public string pass_NHT { get; set; }
        public string name_NHT { get; set; }
        public Nullable<long> phone_NHT { get; set; }
        public string email_NHT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QG> tbl_QG { get; set; }
        public string confirmPassword { get; internal set; }
    }
}
