//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GQNA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QG
    {
        public long id_HD { get; set; }
        public Nullable<int> id_NHT { get; set; }
        public Nullable<int> id_project { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public DateTime NgayQuyenGop { get; set; }
        public string TrangThai { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual tbl_NHT tbl_NHT { get; set; }
    }
}
