//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GQNA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_img
    {
        public int id_img { get; set; }
        public Nullable<int> id_project { get; set; }
        public string url_img { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
